# Generated by Django 4.1.4 on 2023-06-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Especie')),
                ('nombreEspecie', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('idTamaño', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Tanaño')),
                ('nombreTamaño', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('nombre', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('genero', models.CharField(blank=True, max_length=50, verbose_name='Genero')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripcion')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotitas.especie', verbose_name='Especie')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotitas.tamaño', verbose_name='Tamaño')),
            ],
        ),
    ]
